version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - todo-app
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db-usr
      MYSQL_PASSWORD: Password1
      MYSQL_ROOT_HOST: '%'
  frontend:
    build: ./
    ports:
      - 4200:80
    links:
      - backend
  backend:
    depends_on:
      - db
    build: ./backend/
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    ports:
      - "5000:5000"
    networks:
      - todo-app
volumes:
  data:
networks:
  todo-app:
    driver: bridge
